version: '3'
services:
  www:
    build:
      context: ./www/
      dockerfile: ./Dockerfile
    image: "docker"
    ports:
      - "80:80"
    volumes:
      - /var/www/html/:/var/www/html/
    command: '/usr/sbin/apache2ctl -D FOREGROUND'
